name: gg

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag gg .
          docker push gg

      # Add deployment steps if needed
      # Example:
      # - name: Deploy to Kubernetes
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      #     namespace: 'default'
      #     manifests: |
      #       ./kubernetes/deployment.yaml

